# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sXIGynbFDTwpi5JNbAT1EONcq5TQYiZY
"""

comments = [
    "I love the art style of manhwa!",
    "Manga has a more unique storytelling approach.",
    "I prefer reading manhwa over manga any day!",
    "Manga often feels more detailed and immersive.",
    "I don't really enjoy either.",
    "Manhwa tends to be more colorful and vibrant!",
    "I dislike how manhwa is often just copying manga.",
    "Both have their strengths, but I like manga better.",
    "Manhwa characters are often more relatable.",
    "I find manga boring compared to manhwa."
]

from textblob import TextBlob

# Initialize counters
positive_count = 0
negative_count = 0

# Analyze each comment
for comment in comments:
    analysis = TextBlob(comment)
    # Classify the sentiment
    if analysis.sentiment.polarity > 0:
        positive_count += 1
    elif analysis.sentiment.polarity < 0:
        negative_count += 1

# Calculate percentages
total_comments = len(comments)
positive_percentage = (positive_count / total_comments) * 100
negative_percentage = (negative_count / total_comments) * 100

# Summary of results
print(f'Total Comments: {total_comments}')
print(f'Positive Comments: {positive_count} ({positive_percentage:.2f}%)')
print(f'Negative Comments: {negative_count} ({negative_percentage:.2f}%)')