# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sXIGynbFDTwpi5JNbAT1EONcq5TQYiZY

How It Works:
Response Dictionary: A dictionary holds predefined responses for specific questions.
Tokenization: The user input is tokenized into words to make it easier to check for keywords.
Keyword Matching: The chatbot checks if any of the keywords from the predefined questions are present in the user input. If found, it returns the corresponding answer.
Interaction Loop: The chatbot runs in a loop, allowing the user to ask questions until they type "exit."
"""

# Define a dictionary of questions and answers
responses = {
    "What is Castle Swimmer about?": "Castle Swimmer is a webtoon that explores themes of adventure, prophecy, and the bonds between characters as they navigate a mystical ocean.",
    "Who are the main characters?": "The main characters include the prince, who is on a quest to fulfill a prophecy, and various companions he meets along the way.",
    "What are the key themes?": "Key themes include friendship, courage, and the struggle against fate.",
    "What happens in chapters 83-89?": "Chapters 83-89 unveil new prophecies and developments that impact the journey of the characters.",
    "Can you tell me more about the prophecy?": "The prophecy serves as a guiding force for the characters, influencing their choices and interactions."
}

import nltk
from nltk.tokenize import word_tokenize

# Ensure you have the necessary NLTK data files
nltk.download('punkt')

def chatbot_response(user_input):
    # Tokenize the user input
    tokens = word_tokenize(user_input.lower())

    # Check for keywords and respond accordingly
    for question, answer in responses.items():
        if any(keyword in tokens for keyword in question.lower().split()):
            return answer

    return "I'm sorry, I don't understand that question."

# Simple loop to interact with the chatbot
print("Welcome to the Castle Swimmer Chatbot! (Type 'exit' to quit)")
while True:
    user_input = input("You: ")
    if user_input.lower() == 'exit':
        break
    response = chatbot_response(user_input)
    print(f"Bot: {response}")